# Generated by Django 3.1.4 on 2021-03-20 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carddesign',
            name='popularity',
            field=models.TextField(choices=[(1, 'Обычная'), (2, 'Редкая'), (3, 'Невероятная')], default=1),
        ),
    ]
