# Generated by Django 3.1.4 on 2021-03-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0002_carddesign_popularity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='battle_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='carddesign',
            name='card_design_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cardsuser',
            name='cards_user_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
