# Generated by Django 3.1.4 on 2021-03-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0003_auto_20210320_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardsuser',
            name='battle_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cardsuser',
            name='battle_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cardsuser',
            name='coins',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cardsuser',
            name='creator_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cardsuser',
            name='win_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
