# Generated by Django 3.1.4 on 2021-03-20 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0004_auto_20210320_0931'),
    ]

    operations = [
        migrations.CreateModel(
            name='BattleRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memes.card')),
            ],
        ),
    ]
