# Generated by Django 3.1.4 on 2021-03-20 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0005_battlerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='battlerequest',
            name='battle',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='memes.battle'),
        ),
        migrations.AlterField(
            model_name='carddesign',
            name='popularity',
            field=models.IntegerField(choices=[(1, 'Обычная'), (2, 'Редкая'), (3, 'Невероятная')], default=1),
        ),
    ]
