# Generated by Django 3.1.4 on 2021-03-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0007_auto_20210320_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardsuser',
            name='last_everyday_reward',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
