# Generated by Django 3.1.4 on 2021-03-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0008_cardsuser_last_everyday_reward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardsuser',
            name='last_everyday_reward',
            field=models.DateTimeField(),
        ),
    ]
