# Generated by Django 3.1.4 on 2021-03-20 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0009_auto_20210320_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='carddesign',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='memes.cardsuser'),
        ),
    ]
