# Generated by Django 3.1.4 on 2021-03-20 16:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0010_carddesign_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='carddesign',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to='memes.CardsUser'),
        ),
        migrations.AlterField(
            model_name='cardsuser',
            name='last_everyday_reward',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=utc)),
        ),
    ]
