# Generated by Django 3.1.4 on 2021-03-20 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0011_auto_20210320_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardsuser',
            name='creator_rating',
        ),
    ]
