# Generated by Django 3.1.4 on 2021-03-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0012_remove_cardsuser_creator_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='carddesign',
            name='intro_card_design',
            field=models.BooleanField(default=False),
        ),
    ]
